import Nav from "@/components/Nav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Nav />
      <body className="mt-20">{children}</body>
    </html>
  )
}
