interface Metadata {
  title: string;
  description: string;
}


const metadata: Metadata = {
  title: 'Binacode Technologies Limited',
  description: 'Generated by create next app',
};

export default metadata;
